### PR TITLE
perf: improve ApplyInstantID performance

### PR DESCRIPTION
**Pull request by JettHu**
`InstantID` is re-instantiated every time `ApplyInstantID` is called, but this is redundant from a parameter point of view. Moving the instantiation of `InstantID` in `ApplyInstantID` to `InstantIDModelLoader` can improve the performance of the `ApplyInstantID` node (and for `InstantIDAttentionPatch`).

### CODE REVIEW

**Comment by cubiq** [comment]
let me talk to the instantid guys, this was done to support further development of instantID models, but as all technologies in this field that doesn't seem to be happening

**Comment by JettHu** [comment]
In addition, does `noise` play a big role in `Apply`? If `uncond_image_prompt_embeds` could cached after first encoded, the performance improvement will be greater.

**Comment by cubiq** [comment]
noise helps quite a bit yeah

**Comment by JettHu** [comment]
> GPU: Tesla T4 8G

Upon merging this PR, the `ApplyInstantID` now completes in approximately 200-300 ms, a significant reduction from the previous time 3300 ms+. I am contemplating open a PR for similar improvements in the `IPAdapter` repo as well.

**Comment by cubiq** [comment]
instantid is simple because we have only one configuration, with ipadapter we have quite a few. it's doable but it needs more work

**Pull request merged**
